### ISSUE TITLE
Add task play

### ISSUE THREAD

**Issue by mudler** [MottainaiCI/mottainai-server#10]

**Comment by geaaru** [comment]
Easier start a new agent in a standalone mode and assign the task with:
```
$> mottainai-cli queue add-task --qid <qid> --t <taskid>
```
or directly to the node:
```
$> mottainai-cli nodequeue add-task --agent-key <agentkey> --node-id <nid>  --t <taskid> -q <queue>
```

**Comment by mudler** [comment]
I'm fine with it, but that's not easier, the issue was about to have a way to replicate it locally

**Comment by geaaru** [comment]
yeah, i know but I prefer to maintain only one piece of code stable over the agent code. I dropped the command `mottainai-cli task execute` too for the same reason.
Thanks for the note.
