### ISSUE TITLE
mottainai-cli: error on create namespace or storage from cli

### ISSUE THREAD

**Issue by kurtz81** [MottainaiCI/mottainai-server#54]
When you create a namespace or storage with a name containing underscore or dot, these characters are deleted from the name:

$ mottainai-cli storage create tic.tac.toe
Processed: true
Status: ok
ObjType: storage
Event: github.com/MottainaiCI/mottainai-server/routes/api/storages.StorageCreate
ID: 6896421963177683178

$ mottainai-cli storage list
2019/09/24 10:17:32 Available storages: 
|         ID          |      NAME       |      PATH       |
|---------------------|-----------------|-----------------|
| 6896421963177683178 | tictactoe       | tictactoe       |

$ mottainai-cli storage create tic_tac_toe
Processed: true
Status: ok
ObjType: storage
Event: github.com/MottainaiCI/mottainai-server/routes/api/storages.StorageCreate
ID: 7663231278675909173

$ mottainai-cli storage list
2019/09/24 10:48:07 Available storages: 
|         ID          |      NAME       |      PATH       |
|---------------------|-----------------|-----------------|
| 7663231278675909173 | tictactoe       | tictactoe       |

**Comment by geaaru** [comment]
Fixed with 3d7e57d1718a494d7a9b2aa435cbed0a255f7c69.
Thanks for the report.
