### ISSUE TITLE
openrc units. attached. 

### ISSUE THREAD

**Issue by necrose99** [MottainaiCI/mottainai-server#67]
[mottainai-openrc-units.zip](https://github.com/MottainaiCI/mottainai-server/files/5171508/mottainai-openrc-units.zip)
**server/agent included.** 

**[infitify.pl ](https://github.com/goose121/initify )** _**from archLinux forums makes units to openrc trivial..**_ 

**however more automatic** 
else **[app-admin/openrc-settingsd](https://packages.gentoo.org/packages/app-admin/openrc-settingsd)**

```
#!/sbin/openrc-run

command=/usr/bin/mottainai-agent
command_args="agent --config /etc/mottainai/mottainai-agent.yaml"
pidfile=

name="mottainai-agent"
description="Mottainai Agent"
```

**Comment by geaaru** [comment]
Hi, thanks for your report.
Can you create a PR and push your script under `contrib/openrc/ directory?
I will add the script also under our overlay.

**Comment by necrose99** [comment]
Yes im happy to do so.. 
Power pin on laptop rma , replacement desktop (wich i haven't in years by Fri or tue at worst) least if 1 fails.. 
So i will apologize now for deylay.

**Comment by geaaru** [comment]
All done here with PR. Thanks again.
