### ISSUE TITLE
Load a "default" profile, if defined

### ISSUE THREAD

**Issue by optiz0r** [MottainaiCI/mottainai-server#9]
It would be good to make mottainai-cli easier to use for repeated use. If profiles could store an apikey, and if a "default" profile could be loaded if it exists, then it would save a lot of typing on the commandline.

**Comment by geaaru** [comment]
Hi, a way to define a default profile is set MOTTAINAI_CLI_PROFILE env variable on your .bashrc. I'm not sure that add default profile on mcli profiles config add additional benefits.

About apikey... just added to mcli: https://github.com/MottainaiCI/mottainai-cli/commit/f8176d786c00fc53add2eb9be1e5fce38ce64ab5
